---
title: "Plots of MDD DEGs"
author: "Chi-Lam Poon"
date: "10/18/2020"
output: html_document
---


For drawing plots.

```{r setup}
suppressPackageStartupMessages({
  library(purrr)
  library(dplyr)
  library(knitr)
  library(ggplot2)
  library(ggpubr)
  library(reshape2)
  library(Biobase)
})
```


### Load data
```{r load}
res.dir <- '~/cvd/v8/results/new/mdd'
```

All tissue names:
```{r tissue-list}
tissues <- c("Adipose - Subcutaneous", "Muscle - Skeletal", "Artery - Tibial", "Artery - Coronary", "Heart - Atrial Appendage",
             "Adipose - Visceral (Omentum)", "Uterus", "Vagina", "Breast - Mammary Tissue", "Skin - Not Sun Exposed (Suprapubic)",
             "Minor Salivary Gland", "Brain - Cortex", "Adrenal Gland", "Thyroid", "Lung", "Spleen", "Pancreas", "Esophagus - Muscularis",
             "Esophagus - Mucosa", "Esophagus - Gastroesophageal Junction", "Stomach", "Colon - Sigmoid", "Small Intestine - Terminal Ileum",
             "Colon - Transverse", "Prostate", "Testis", "Nerve - Tibial", "Skin - Sun Exposed (Lower leg)", "Heart - Left Ventricle", 
             "Brain - Cerebellum", "Whole Blood", "Artery - Aorta", "Pituitary", "Brain - Frontal Cortex (BA9)",
             "Brain - Caudate (basal ganglia)", "Brain - Nucleus accumbens (basal ganglia)", "Brain - Putamen (basal ganglia)",
             "Brain - Hypothalamus", "Brain - Spinal cord (cervical c-1)", "Brain - Hippocampus",
             "Brain - Anterior cingulate cortex (BA24)", "Ovary", "Brain - Cerebellar Hemisphere", "Liver", "Brain - Substantia nigra")
```


### 1. Numbers of DE genes
```{r}
table.dir <- file.path(res.dir, 'tables')
FCthres <- 1.5
Pthres <- 0.05

# Plot DEG numbers for all tissues
sc_df <- data.frame(tissue = tissues, total = rep(0, length(tissues)), 
                    up = rep(0, length(tissues)), down = rep(0, length(tissues)))

for (i in tissues) {
  tmp <- read.table(file.path(table.dir, paste0(i, ".txt")), sep="\t", header=T)
  tmp <- tmp[!is.na(tmp$logFC),]
  sc_df[sc_df$tissue==i,]$total <- nrow(tmp[(tmp$adj.P.Val < Pthres) & (abs(tmp$logFC) > log2(FCthres)),])
  sc_df[sc_df$tissue==i,]$up <- nrow(tmp[(tmp$adj.P.Val < Pthres) & (tmp$logFC > log2(FCthres)),])
  sc_df[sc_df$tissue==i,]$down <- nrow(tmp[(tmp$adj.P.Val < Pthres) & (tmp$logFC < -log2(FCthres)),])
}

sc_df <- sc_df[sc_df$total != 0,]
sc_df <- sc_df[order(sc_df$tissue),]
long <- melt(sc_df, id.vars = 'tissue')
long <- long[long$variable!='total',]
print(sc_df)

ggplot(data=long, aes(x=tissue, y=value, fill=variable)) +
  geom_bar(stat="identity", position="dodge") +
  scale_x_discrete(limits=rev(sc_df$tissue), labels=rev(gsub("_", " ", sc_df$tissue))) +
  scale_y_continuous(limits=c(0, 50), expand = c(0.02, 0)) +
  geom_text(position = position_dodge(width= 0.9), aes(y=value, label=value, hjust=-0.2), size=2.7) +
  labs(title="Major Depression", x="", y="", fill=" ") +  
  scale_fill_manual(labels = c("Up", "Down"),values=c('#4983a2','#d0e6df')) +
  coord_flip() + theme_classic()
```


### DEG overlap

```{r}
sel.tissues <- sc_df$tissue
table.dir <- file.path(res.dir, 'tables')

deg.list <- list()
for (t in sel.tissues) {
  tmp <- read.table(file.path(table.dir, paste0(t, ".txt")), sep="\t", header=T)
  tmp <- tmp[!is.na(tmp$logFC),]
  
  deg.list[[t]] <- list()
  deg.list[[t]][['total']] <- tmp[(tmp$adj.P.Val < Pthres) & (abs(tmp$logFC) > log2(FCthres)),]
  deg.list[[t]][['up']] <- tmp[(tmp$adj.P.Val < Pthres) & (tmp$logFC > log2(FCthres)),]
  deg.list[[t]][['down']] <- tmp[(tmp$adj.P.Val < Pthres) & (tmp$logFC < -log2(FCthres)),]
}


## Venn diagrams
library(venn)
v.up <- venn(list(`Brain - Hypothalamus`=deg.list[['Brain - Hypothalamus']]$up$ID,
                  `Brain - Putamen`=deg.list[['Brain - Putamen (basal ganglia)']]$up$ID,
                  `Whole Blood`=deg.list[['Whole Blood']]$up$ID,
                  `Brain - Spinal cord`=deg.list[['Brain - Spinal cord (cervical c-1)']]$up$ID),
                  intersections = T, box = F)

v.down <- venn(list(`Brain - Hypothalamus`=deg.list[['Brain - Hypothalamus']]$down$ID,
                    `Brain - Putamen`=deg.list[['Brain - Putamen (basal ganglia)']]$down$ID,
                    `Whole Blood`=deg.list[['Whole Blood']]$down$ID,
                    `Brain - Spinal cord`=deg.list[['Brain - Spinal cord (cervical c-1)']]$down$ID),
                    intersections = T, box = F)
v.all <- venn(list(`Brain - Hypothalamus`=deg.list[['Brain - Hypothalamus']]$total$ID,
                   `Brain - Putamen`=deg.list[['Brain - Putamen (basal ganglia)']]$total$ID,
                   `Brain - Spinal cord`=deg.list[['Brain - Spinal cord (cervical c-1)']]$total$ID),
                    intersections = T, box = F, zcol = "#ffdd77, #bb2020, #1188cc")
```


Try `eulerr` package:
```{r}
library(eulerr)
wanted <- c('Brain - Hypothalamus', 'Brain - Putamen (basal ganglia)', 'Brain - Spinal cord (cervical c-1)')
length(deg.list[[wanted[1]]]$total$ID); length(deg.list[[wanted[2]]]$total$ID)
length(deg.list[[wanted[3]]]$total$ID)
intersect(deg.list[[wanted[1]]]$total$ID, deg.list[[wanted[2]]]$total$ID)
intersect(deg.list[[wanted[1]]]$total$ID, deg.list[[wanted[3]]]$total$ID)
intersect(deg.list[[wanted[2]]]$total$ID, deg.list[[wanted[3]]]$total$ID)
intersect(deg.list[[wanted[1]]]$total$ID, intersect(deg.list[[wanted[2]]]$total$ID, deg.list[[wanted[3]]]$total$ID))
eulerr.vec <- c("Brain - Hypothalamus" = 53, "Brain - Putamen" = 28, "Brain - Spinal cord" = 14, 
                "Brain - Hypothalamus&Brain - Putamen"=0, "Brain - Putamen&Brain - Spinal cord"=0,
                "Brain - Hypothalamus&Brain - Spinal cord"=0,"Brain - Hypothalamus&Brain - Putamen&Brain - Spinal cord"=0
                )                                                                                           
fit <- euler(eulerr.vec, shape = "ellipse")
plot(fit, opacity = .7, quantities = TRUE, lwd = 1)
```
Hmmm not good


### Comparison of CVD DEGs
```{r compare, eval=F}
cvd.deg <- readRDS('~/cvd/v8/results/new/noRACE/sig.deg.rds')
cvd.deg <- cvd.deg[names(cvd.deg) %in% names(deg.list)]
for (tissue in names(cvd.deg)) {
  cvd.genes <- cvd.deg[[tissue]]$total$ID
  mdd.genes <- deg.list[[tissue]]$total$ID
  intersect <- intersect(cvd.genes, mdd.genes)
  if (length(intersect) > 0) {
    print(paste('Tissue '), tissue, '...')
    print(intersect)
  }
}
```

Nothing!!!!

### Save
```{r}
saveRDS(deg.list, file=file.path(res.dir,'sig.deg.rds'))
```


